{
 "title": "CouchDB Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "Instance Name",
    "query": "label_values(couchdb_httpd_up, instance)"
   },
   {
    "name": "MethodName",
    "label": "Method Name",
    "query": "label_values(couchdb_httpd_request_methods, method)"
   },
   {
    "name": "DBName",
    "label": "DB Name",
    "query": "label_values(couchdb_database_disk_size, db_name)"
   }
  ]
 },
 "panels": [
  { "title": "$InstanceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "InstanceName" },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "couchdb_server_node_info{instance=\"$InstanceName\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Total number of databases in the cluster",
   "type": "singlestat",
   "description": "Total number of databases in the cluster",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchdb_httpd_databases_total{instance=\"$InstanceName\"}"
    }
   ]
  },
  {
   "title": "Total Disk Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 1 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(couchdb_database_disk_size{instance=\"$InstanceName\"})"
    }
   ]
  },
  {
   "title": "Number of CouchDB Nodes Available",
   "type": "singlestat",
   "description": "Number of CouchDB Nodes Available",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "couchdb_httpd_node_up{instance=\"$InstanceName\"}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=~\"$InstanceName.+\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "couchdb_erlang_memory_binary{instance=\"$InstanceName\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "couchdb_erlang_memory_atomd{instance=\"$InstanceName\"}",
     "legendFormat": "Atomd"
    },
    {
     "expr": "couchdb_erlang_memory_processes{instance=\"$InstanceName\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "couchdb_erlang_memory_code{instance=\"$InstanceName\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "couchdb_erlang_memory_ets{instance=\"$InstanceName\"}",
     "legendFormat": "ETS"
    },
    {
     "expr": "couchdb_erlang_memory_other{instance=\"$InstanceName\"}",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Document Count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, couchdb_database_doc_count{instance=\"$InstanceName\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "CouchDB HTTPD Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(couchdb_httpd_requests{instance=\"$InstanceName\"}[5m])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CouchDB HTTP Request per Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(couchdb_httpd_request_methods{instance=\"$InstanceName\"}[5m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "CouchDB number of clients for continuous changes",
   "type": "graph",
   "description": "number of clients for continuous _changes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "couchdb_httpd_clients_requesting_changes{instance=\"$InstanceName\"}",
     "legendFormat": "Clients changes"
    }
   ]
  },
  {
   "title": "CouchDB Open OS Files",
   "type": "graph",
   "description": "number of file descriptors CouchDB has open",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "couchdb_httpd_open_os_files{instance=\"$InstanceName\"}",
     "legendFormat": "Open Files"
    }
   ]
  }
 ]
}