---
version: "3.3"

services:
  couchdb:
    image: couchdb:2.3.1
    volumes:
      - couchdb-data:/opt/couchdb/data
    networks:
      - couchdb
    ports:
      - "5984:5984"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  couchdb-config:
    image: gesellix/wait-for:latest
    command: couchdb:5984 --timeout=30 -- /cluster-config.sh couchdb:5984 /run/secrets/config.properties
    networks:
      - couchdb
    configs:
      - source: cluster-config-script
        target: /cluster-config.sh
        mode: 0555
    secrets:
      - source: exporter-config
        target: config.properties
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2

  couchdbstats:
    image: gesellix/couchdb-prometheus-exporter:latest
    command: --couchdb.uri=http://couchdb:5984 --config=/run/secrets/config.properties
    networks:
      - couchdb
    ports:
      - "9984:9984"
    secrets:
      - source: exporter-config
        target: config.properties
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  couchdb:

volumes:
  couchdb-data:
#    external: true

secrets:
  exporter-config:
    file: config.properties

configs:
  cluster-config-script:
    file: cluster-config.sh
